"$schema" = 'https://starship.rs/config-schema.json'

# delete newline
add_newline = false

# left prompt
format = """
$username@$hostname [on](white) $directory $fill $git_branch $git_status $nodejs $php $java $python
$character"""

right_format = '''
$cmd_duration $time $battery
'''

[character] # The name of the module we are configuring is 'character'
success_symbol = '[ﬦ](bold green)'
error_symbol = '[x](bold red)'

[cmd_duration]
format = '[$duration]($style)'
style = 'yellow'

[username]
style_user = '#cd5ad7 bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ' '
format = '[$ssh_symbol](bold blue)[$hostname](bold red)'
trim_at = '.companyname.com'
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = ' '
truncation_symbol = ''
style = 'bold white'

[git_status]
format = ' [$all_status$ahead_behind]($style)'
modified = '凜'
staged = '[++\($count\)](green)'
deleted = '[﫧](red)'

[nodejs]
format = '[ $version](bold green)'
version_format = '${major}.${minor}'

[python]
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
style = 'yellow bold'
pyenv_version_name = true

[php]
format = ' [ $version](blue bold)'

[time]
format = '[$time]($style)'
use_12hr = false
time_format = '%R'
disabled = false
time_range = '-'
style = 'white bold'

[battery]
disabled = false
format = '[$symbol $percentage]($style)'
full_symbol = '[](bold green)'
empty_symbol = '[](bold red)'
charging_symbol = '[](bold yellow)'


[[battery.display]]
threshold = 100
style = 'bold green'
discharging_symbol = ''
charging_symbol = ''

[[battery.display]]
threshold = 10
style = 'bold red'
discharging_symbol = ''
charging_symbol = ''

[[battery.display]]
threshold = 30
style = 'bold red'
discharging_symbol = ''
charging_symbol = ''

[[battery.display]]
threshold = 50
style = 'bold yellow'
discharging_symbol = ''
charging_symbol = ''

[[battery.display]]
threshold = 70
style = 'bold yellow'
discharging_symbol = ''
charging_symbol = ''

[fill]
symbol=' '